config/routes.rb
Rails.application.routes.draw do
  # Autenticação com Devise
  devise_for :users

  # Página inicial apontando para a listagem de carros
  root 'cars#index'

  # Rotas de carros
  resources :cars, only: [:index, :show]

  
  # Carrinho de aluguel
  resource :cart, only: [:show] do
    post 'add_item'
    delete 'remove_item'
    post 'checkout', on: :collection
  end

  #rotas de reservas
  resources :reservations, only: [:index, :new, :create] do
    member do
      patch :cancel
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Usuário convidado (não autenticado)

    if user.admin?
      can :manage, :all  # Admin pode gerenciar tudo
    else
      can :read, Car   # Usuário comum pode ver a lista de carros
      can :manage, ::Cart, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :manufacturer
    has_many :cart_items
    has_many :carts, through: :cart_items
    has_many :reservation_items
    has_many :reservations, through: :reservation_items
    
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :cart_items, dependent: :destroy
end
  

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :car
  
    validates :quantity, numericality: { greater_than: 0 }
  end
  

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :cars
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_many :reservation_items, dependent: :destroy
  has_many :cars, through: :reservation_items
end

app/models/reservation_item.rb
class ReservationItem < ApplicationRecord
  belongs_to :reservation
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :cpf, presence: true, uniqueness: true, format: { with: /\A\d{11}\z/, message: "deve ter 11 dígitos numéricos" }

  attribute :admin, :boolean, default: false
  has_many :reservations, dependent: :destroy
  has_one :cart, class_name: "Cart", foreign_key: "user_id", dependent: :destroy
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :cpf])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :cpf])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #skip_before_action :authenticate_user!, only: [:index]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @cars = Car.all
    @cars = @cars.where(manufacturer_id: params[:manufacturer]) if params[:manufacturer].present?
    @cars = @cars.where("model LIKE ?", "#{params[:model]}%") if params[:model].present?
    @cars = @cars.where(fuel_type: params[:fuel_type]) if params[:fuel_type].present?
    @cars = @cars.where(transmission: params[:transmission]) if params[:transmission].present?
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def add_item
    @cart = current_user.cart || current_user.create_cart(status: 'active')

    quantity = params[:quantity].to_i
    quantity = 1 if quantity <= 0

    item = @cart.cart_items.find_by(car_id: params[:car_id])

    if item
      item.update(quantity: item.quantity + quantity)
    else
      @cart.cart_items.create(car_id: params[:car_id], quantity: quantity)
    end

    redirect_to cart_path, notice: 'Carro adicionado ao carrinho!'
  end

  def remove_item
    @cart = current_user.cart
    item = @cart.cart_items.find_by(car_id: params[:car_id])

    if item
      item.destroy
      flash[:notice] = 'Carro removido do carrinho!'
    else
      flash[:alert] = 'Carro não encontrado no carrinho.'
    end

    redirect_to cart_path
  end

  def show
    @cart = current_user.cart || current_user.create_cart(status: 'active')
  end

  def checkout
    @cart = current_user.cart
    if @cart.cart_items.empty?
      redirect_to cart_path, alert: "Seu carrinho está vazio!"
    else
      redirect_to new_reservation_path
    end
  end

  def set_cart
    @cart = current_user.cart || current_user.create_cart(status: 'active')
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservations.includes(:reservation_items) || []
  end

  def new
    @cart = current_user.cart || current_user.create_cart(status: 'active')
    if @cart.cart_items.empty?
      redirect_to cart_path, alert: "Seu carrinho está vazio!"
    else
      @reservation = Reservation.new
    end
  end

  def create
    @cart = current_user.cart
    @reservation = current_user.reservations.build(reservation_params)

    # Cálculo do preço total baseado nos itens do carrinho
    total_price = 0
    @cart.cart_items.each do |item|
      total_price += item.car.daily_rental_price * (reservation_params[:end_date].to_date - reservation_params[:start_date].to_date).to_i * item.quantity
    end

    @reservation.total_price = total_price # Definindo o preço total

    if @reservation.save
      # Criando os itens da reserva
      @cart.cart_items.each do |cart_item|
        @reservation.reservation_items.create(
          car: cart_item.car,
          quantity: cart_item.quantity
        )
      end

      # Finalizando o carrinho
      @cart.update(status: 'completed')
      @cart.cart_items.destroy_all

      redirect_to reservations_path, notice: "Reserva realizada com sucesso!"
    else
      render :new
    end
  end

  def cancel
    @reservation = current_user.reservations.find(params[:id])

    if @reservation.start_date > Date.today
      @reservation.destroy
      redirect_to reservations_path, notice: "Reserva cancelada com sucesso."
    else
      redirect_to reservations_path, alert: "Não é possível cancelar uma reserva que já começou."
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    # Exibe o formulário de login
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Login realizado com sucesso!'
    else
      flash.now[:alert] = 'E-mail ou senha inválidos'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logout realizado com sucesso!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'Usuário criado com sucesso!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :cpf, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  def generate_image_url(car, angle = '0')
    base_url = 'https://cdn.imagin.studio/getimage'

    params = {
      customer: 'hrjavascript-mastery',
      make: car.manufacturer.name,
      modelFamily: car.model.split(' ').first,
      zoomType: 'fullscreen',
      modelYear: car.year,
      angle: angle
    }

    url = "#{base_url}?#{params.to_query}"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_car_card.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow">
    <img src="<%= generate_image_url(car) %>" class="card-img-top" alt="<%= car.model %>">
    <div class="card-body">
      <h5 class="card-title"><%= car.manufacturer.name %> <%= car.model %> (<%= car.year %>)</h5>
      <p class="card-text">
        <strong>Combustível:</strong> <%= car.fuel_type %><br>
        <strong>Transmissão:</strong> <%= car.transmission == 'a' ? 'Automático' : 'Manual' %><br>
        <strong>Tração:</strong> <%= car.drive&.upcase || 'N/A' %><br>
        <strong>Consumo:</strong> <%= (car.city_mpg.to_f * 0.43).round(2) %> Km/L<br>
        <strong>Preço:</strong> <%= number_to_currency(car.price) %><br>
        <strong>Preço Diário de Aluguel:</strong> <%= number_to_currency(car.daily_rental_price) %><br>
      </p>
      <div class="d-grid">
        <%= button_to 'Adicionar ao Carrinho', add_item_cart_path(car_id: car.id), method: :post, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Carros Disponíveis</h1>

  <%= form_with url: cars_path, method: :get, local: true, class: "mb-4" do |form| %>
    <div class="row g-3">
    <div class="col-md-2 me-md-3">
      <%= form.label :model, 'Modelo', class: 'form-label' %>
      <%= form.text_field :model, value: params[:model], class: "form-control", placeholder: "Digite o modelo", style: "max-width: 100%" %>
    </div>

    <div class="col-md-3">
      <%= form.label :manufacturer, 'Fabricante', class: 'form-label' %>
      <%= form.select :manufacturer, Manufacturer.all.collect { |m| [m.name, m.id] }, 
          include_blank: 'Selecione o Fabricante', 
          selected: params[:manufacturer], 
          class: "form-control" %>
    </div>


      <div class="col-md-3">
        <%= form.label :fuel_type, 'Tipo de Combustível', class: 'form-label' %>
        <%= form.select :fuel_type, 
            [['Elétrico', 'electric'], ['Diesel', 'diesel'], ['Gasolina', 'gas']], 
            include_blank: 'Selecione o Combustível', 
            selected: params[:fuel_type], 
            class: "form-control" %>
      </div>

      <div class="col-md-3">
        <%= form.label :transmission, 'Transmissão', class: 'form-label' %>
        <%= form.select :transmission, 
            [['Automático', 'a'], ['Manual', 'm']], 
            include_blank: 'Selecione a Transmissão', 
            selected: params[:transmission], 
            class: "form-control" %>
      </div>

      <div class="col-md-1 d-flex align-items-end">
        <%= form.submit 'Filtrar', class: "btn btn-success w-100" %>
      </div>
    </div>
  <% end %>

  <div class="row mt-4">
    <% @cars.each do |car| %>
      <%= render 'cars/car_card', car: car %>
    <% end %>
  </div>
</div>

app/views/cart/show.htlm.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Seu Carrinho</h1>

  <% if @cart && @cart.cart_items.any? %>
    <div class="row">
      <% @cart.cart_items.each do |item| %>
        <div class="col-md-6 col-lg-4">
          <div class="card mb-4 shadow-sm">
            <img src="<%= generate_image_url(item.car) %>" class="card-img-top" alt="<%= item.car.model %>">
            <div class="card-body">
              <h5 class="card-title text-center"><%= item.car.manufacturer.name %> <%= item.car.model %></h5>
              <p class="card-text text-center">
                <strong>Quantidade:</strong> <%= item.quantity %> <br>
                <strong>Combustível:</strong> <%= item.car.fuel_type %> <br>
                <strong>Transmissão:</strong> <%= item.car.transmission == 'a' ? 'Automático' : 'Manual' %><br>
                <strong>Preço Diário de Aluguel:</strong> <%= number_to_currency(item.car.daily_rental_price) %><br>
                </p>
              <div class="d-flex justify-content-between">
                <%= button_to 'Remover', remove_item_cart_path(car_id: item.car.id), method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="text-center mt-4">
      <%= button_to 'Finalizar Compra', checkout_cart_path, method: :post, class: "btn btn-success btn-lg px-5" %>
    </div>
  
  <% else %>
    <div class="alert alert-warning text-center mt-4">
      <h4>Seu carrinho está vazio.</h4>
      <p>Explore nossos carros disponíveis e adicione os que deseja alugar!</p>
      <%= link_to "Ver Carros", cars_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/carts/show.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4">Seu Carrinho</h1>

  <% if @cart && @cart.cart_items.any? %>
    <div class="row">
      <% @cart.cart_items.each do |item| %>
        <div class="col-md-6 col-lg-4">
          <div class="card mb-4 shadow-sm">
            <img src="<%= generate_image_url(item.car) %>" class="card-img-top" alt="<%= item.car.model %>">
            <div class="card-body">
              <h5 class="card-title text-center"><strong> <%= item.car.manufacturer.name %> <%= item.car.model %> </strong></h5>
              <p class="card-text text-center">
                <strong>Quantidade:</strong> <%= item.quantity %> <br>
                <strong>Combustível:</strong> <%= item.car.fuel_type %> <br>
                <strong>Transmissão:</strong> <%= item.car.transmission == 'a' ? 'Automático' : 'Manual' %><br>
                <strong>Preço Diário de Aluguel:</strong> <%= number_to_currency(item.car.daily_rental_price) %><br>
              </p>
              <div class="d-flex justify-content-between">
                <%= button_to 'Remover', remove_item_cart_path(car_id: item.car.id), method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="text-center mt-4">
      <%= button_to 'Finalizar Compra', checkout_cart_path, method: :post, class: "btn btn-success btn-lg px-5" %>
    </div>
  
  <% else %>
    <div class="alert alert-warning text-center mt-4">
      <h4>Seu carrinho está vazio.</h4>
      <p>Explore nossos carros disponíveis e adicione os que deseja alugar!</p>
      <%= link_to "Ver Carros", cars_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>